@startuml Observer Pattern
interface IModerationObserver {
    + OnViolationProcessed(user: User, violation: IViolation)
}
class LoggingModerationObserver
IModerationObserver <|.. LoggingModerationObserver
@enduml
